-- =============================================================================
-- Product Follow-up Tracker — initial database schema
-- =============================================================================
-- HOW TO RUN THIS:
--   1. Open your project at https://supabase.com/dashboard
--   2. Click "SQL Editor" in the left sidebar
--   3. Click "New query"
--   4. Paste this entire file
--   5. Click "Run" (or press Ctrl/Cmd + Enter)
--   6. You should see "Success. No rows returned"
--
-- This file is safe to run once on a fresh project. It creates every table,
-- index, and security rule the app needs. Nothing in here ever exposes one
-- user's data to another user — that's enforced by "Row Level Security"
-- policies below, not by the application code, so it holds even if a bug
-- ever slipped into the app itself.
-- =============================================================================

-- Required for gen_random_uuid()
create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- profiles
-- One row per user, created automatically when someone signs up.
-- Stores app-specific preferences that aren't part of Supabase Auth itself.
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  default_followup_days integer not null default 3,
  timezone text not null default 'Asia/Kolkata',
  date_format text not null default 'DD/MM/YYYY',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is 'One row per authenticated user; app-level profile and preferences.';

-- -----------------------------------------------------------------------------
-- requests
-- The core entity: one "Product Request" = one email/issue conversation
-- with the Product Team.
-- -----------------------------------------------------------------------------
create table if not exists public.requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,

  -- Human-friendly sequential ID like REQ-001, REQ-002, ...
  seq bigint generated by default as identity,
  code text generated always as ('REQ-' || lpad(seq::text, 3, '0')) stored,

  -- Basic information
  title text not null,
  description text,
  product text not null,
  request_type text not null,
  priority text not null default 'medium'
    check (priority in ('low', 'medium', 'high', 'critical')),
  status text not null default 'draft'
    check (status in (
      'draft', 'sent', 'waiting_for_product', 'product_reviewing',
      'in_progress', 'eta_provided', 'waiting_for_release',
      'resolved', 'closed', 'rejected', 'cancelled'
    )),
  owner_contact text,

  -- Email information
  email_subject text,
  product_team_email text,
  original_email_date date,
  email_thread_ref text,
  email_url text,

  -- Tracking information
  eta_date date,
  next_follow_up_date date,
  last_follow_up_date date,
  follow_up_count integer not null default 0,
  resolution_date date,

  -- Additional information
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint title_not_blank check (btrim(title) <> '')
);

comment on table public.requests is 'One row per Product Request (an email/issue conversation with the Product Team).';

-- -----------------------------------------------------------------------------
-- request_activity
-- Append-only timeline of everything that happened to a request.
-- -----------------------------------------------------------------------------
create table if not exists public.request_activity (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  activity_type text not null,
  description text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

comment on table public.request_activity is 'Append-only activity/timeline entries for a request.';

-- -----------------------------------------------------------------------------
-- follow_ups
-- Individual follow-up reminders tied to a request. next_follow_up_date on
-- the request itself drives the dashboard; this table keeps history of every
-- follow-up scheduled/completed over the life of the request.
-- -----------------------------------------------------------------------------
create table if not exists public.follow_ups (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  due_date date not null,
  status text not null default 'pending'
    check (status in ('pending', 'completed', 'rescheduled', 'cancelled')),
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

comment on table public.follow_ups is 'Individual follow-up reminders/history for a request.';

-- -----------------------------------------------------------------------------
-- tags + request_tags
-- Simple many-to-many tagging.
-- -----------------------------------------------------------------------------
create table if not exists public.tags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

comment on table public.tags is 'Tag vocabulary, scoped per user.';

create table if not exists public.request_tags (
  request_id uuid not null references public.requests (id) on delete cascade,
  tag_id uuid not null references public.tags (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (request_id, tag_id)
);

comment on table public.request_tags is 'Join table linking requests to tags.';

-- =============================================================================
-- Indexes
-- =============================================================================
create index if not exists idx_requests_user_id on public.requests (user_id);
create index if not exists idx_requests_status on public.requests (status);
create index if not exists idx_requests_priority on public.requests (priority);
create index if not exists idx_requests_next_follow_up_date on public.requests (next_follow_up_date);
create index if not exists idx_requests_eta_date on public.requests (eta_date);
create index if not exists idx_requests_created_at on public.requests (created_at);

create index if not exists idx_request_activity_user_id on public.request_activity (user_id);
create index if not exists idx_request_activity_request_id on public.request_activity (request_id);

create index if not exists idx_follow_ups_user_id on public.follow_ups (user_id);
create index if not exists idx_follow_ups_request_id on public.follow_ups (request_id);
create index if not exists idx_follow_ups_due_date on public.follow_ups (due_date);

create index if not exists idx_tags_user_id on public.tags (user_id);
create index if not exists idx_request_tags_user_id on public.request_tags (user_id);
create index if not exists idx_request_tags_request_id on public.request_tags (request_id);

-- =============================================================================
-- updated_at trigger — keeps "Last Updated" accurate automatically
-- =============================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists trg_requests_updated_at on public.requests;
create trigger trg_requests_updated_at
  before update on public.requests
  for each row execute function public.set_updated_at();

-- =============================================================================
-- Auto-create a profile row whenever someone signs up
-- =============================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_on_auth_user_created on auth.users;
create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =============================================================================
-- Auto-log activity on request creation and key field changes
-- =============================================================================
create or replace function public.log_request_activity()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.request_activity (request_id, user_id, activity_type, description)
    values (new.id, new.user_id, 'created', 'Request created');
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if new.status is distinct from old.status then
      insert into public.request_activity (request_id, user_id, activity_type, description)
      values (new.id, new.user_id, 'status_changed',
        'Status changed: ' || old.status || ' -> ' || new.status);
    end if;

    if new.priority is distinct from old.priority then
      insert into public.request_activity (request_id, user_id, activity_type, description)
      values (new.id, new.user_id, 'priority_changed',
        'Priority changed: ' || old.priority || ' -> ' || new.priority);
    end if;

    if new.eta_date is distinct from old.eta_date then
      insert into public.request_activity (request_id, user_id, activity_type, description)
      values (new.id, new.user_id, 'eta_changed',
        case when new.eta_date is null then 'ETA removed'
             else 'ETA set: ' || to_char(new.eta_date, 'FMMonth DD, YYYY') end);
    end if;

    if new.next_follow_up_date is distinct from old.next_follow_up_date then
      insert into public.request_activity (request_id, user_id, activity_type, description)
      values (new.id, new.user_id, 'followup_scheduled',
        case when new.next_follow_up_date is null then 'Next follow-up cleared'
             else 'Next follow-up set: ' || to_char(new.next_follow_up_date, 'FMMonth DD, YYYY') end);
    end if;

    if new.resolution_date is distinct from old.resolution_date and new.resolution_date is not null then
      insert into public.request_activity (request_id, user_id, activity_type, description)
      values (new.id, new.user_id, 'resolved', 'Request marked resolved');
    end if;

    return new;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_requests_log_activity on public.requests;
create trigger trg_requests_log_activity
  after insert or update on public.requests
  for each row execute function public.log_request_activity();

-- =============================================================================
-- Row Level Security — every table is private to its owner
-- =============================================================================
alter table public.profiles enable row level security;
alter table public.requests enable row level security;
alter table public.request_activity enable row level security;
alter table public.follow_ups enable row level security;
alter table public.tags enable row level security;
alter table public.request_tags enable row level security;

-- profiles: a user can only see/update their own profile row.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- Profiles are inserted by the handle_new_user trigger (security definer),
-- so no insert policy is needed for normal use.

-- requests: full CRUD, but only on rows the user owns.
drop policy if exists "requests_select_own" on public.requests;
create policy "requests_select_own" on public.requests
  for select using (auth.uid() = user_id);

drop policy if exists "requests_insert_own" on public.requests;
create policy "requests_insert_own" on public.requests
  for insert with check (auth.uid() = user_id);

drop policy if exists "requests_update_own" on public.requests;
create policy "requests_update_own" on public.requests
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "requests_delete_own" on public.requests;
create policy "requests_delete_own" on public.requests
  for delete using (auth.uid() = user_id);

-- request_activity: read-only from the app's point of view (rows are written
-- by triggers/server code acting as the owning user), but scoped per user.
drop policy if exists "request_activity_select_own" on public.request_activity;
create policy "request_activity_select_own" on public.request_activity
  for select using (auth.uid() = user_id);

drop policy if exists "request_activity_insert_own" on public.request_activity;
create policy "request_activity_insert_own" on public.request_activity
  for insert with check (auth.uid() = user_id);

-- follow_ups: full CRUD scoped per user.
drop policy if exists "follow_ups_select_own" on public.follow_ups;
create policy "follow_ups_select_own" on public.follow_ups
  for select using (auth.uid() = user_id);

drop policy if exists "follow_ups_insert_own" on public.follow_ups;
create policy "follow_ups_insert_own" on public.follow_ups
  for insert with check (auth.uid() = user_id);

drop policy if exists "follow_ups_update_own" on public.follow_ups;
create policy "follow_ups_update_own" on public.follow_ups
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "follow_ups_delete_own" on public.follow_ups;
create policy "follow_ups_delete_own" on public.follow_ups
  for delete using (auth.uid() = user_id);

-- tags: full CRUD scoped per user.
drop policy if exists "tags_select_own" on public.tags;
create policy "tags_select_own" on public.tags
  for select using (auth.uid() = user_id);

drop policy if exists "tags_insert_own" on public.tags;
create policy "tags_insert_own" on public.tags
  for insert with check (auth.uid() = user_id);

drop policy if exists "tags_update_own" on public.tags;
create policy "tags_update_own" on public.tags
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "tags_delete_own" on public.tags;
create policy "tags_delete_own" on public.tags
  for delete using (auth.uid() = user_id);

-- request_tags: full CRUD scoped per user.
drop policy if exists "request_tags_select_own" on public.request_tags;
create policy "request_tags_select_own" on public.request_tags
  for select using (auth.uid() = user_id);

drop policy if exists "request_tags_insert_own" on public.request_tags;
create policy "request_tags_insert_own" on public.request_tags
  for insert with check (auth.uid() = user_id);

drop policy if exists "request_tags_delete_own" on public.request_tags;
create policy "request_tags_delete_own" on public.request_tags
  for delete using (auth.uid() = user_id);

-- =============================================================================
-- Done. You should see every table listed under Database -> Tables now.
-- =============================================================================
